import './global.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Navbar from "@/components/Navbar/Navbar";
import {Toaster} from "@/components/ui/toaster";
import {UserDataProvider} from "@/context/UserDataContext";

const inter = Inter({subsets: ['cyrillic-ext']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">

        <body className={inter.className}>
        <main className='h-screen flex flex-col justify-center items-center'>
            <UserDataProvider>
                <Navbar/>
                {children}
            </UserDataProvider>

        </main>
        <Toaster />
        </body>
        </html>
    )
}
